"""
Bharat Voice AI — Safety Guardrails & Escalation Handler

Implements input and output safety checks:
- Refuses illegal activities, dangerous instructions, medical/legal/financial advice.
- Prevents prohibited claims (claiming humanity, authority verification, external actions).
- Provides reusable escalation scripts.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from agent.logger import COMPONENT_AGENT, get_logger

logger = get_logger(COMPONENT_AGENT)

# Standardized Day 2 Escalation Script
DEFAULT_ESCALATION_RESPONSE = (
    "I'm sorry, I can't safely help with that. "
    "Please contact the appropriate professional or official service. "
    "Is there something else I can help you with today?"
)


@dataclass(frozen=True)
class GuardrailResult:
    """Result of a guardrail safety check."""

    is_safe: bool
    category: str | None = None
    refusal_message: str | None = None


# Patterns matching forbidden user intents/requests
GUARDRAIL_PATTERNS: dict[str, list[re.Pattern[str]]] = {
    "illegal_or_violence": [
        re.compile(
            r"\b(bomb|explosive|weapon|gun|kill|attack|murder|assassinate)\b",
            re.IGNORECASE,
        ),
        re.compile(
            r"\b(hack|malware|virus|trojan|ddos|bypass password)\b", re.IGNORECASE
        ),
        re.compile(r"\b(drug|cocaine|heroin|meth|illegal substance)\b", re.IGNORECASE),
        re.compile(r"\b(suicide|self harm|cut myself|end my life)\b", re.IGNORECASE),
        re.compile(r"\b(hate speech|genocide|terrorist)\b", re.IGNORECASE),
    ],
    "sensitive_data": [
        re.compile(
            r"\b(otp|one time password|cvv|pin number|bank password)\b", re.IGNORECASE
        ),
        re.compile(
            r"\b(credit card number|debit card number|atm pin)\b", re.IGNORECASE
        ),
        re.compile(
            r"\b(fake aadhaar|fake passport|fake id|identity theft)\b", re.IGNORECASE
        ),
    ],
    "medical_or_legal": [
        re.compile(
            r"\b(diagnose|medical prescription|prescription|illness|cure my|doctor advice)\b",
            re.IGNORECASE,
        ),
        re.compile(
            r"\b(legal representation|lawsuit advice|court ruling)\b", re.IGNORECASE
        ),
    ],
    "financial_or_government_approval": [
        re.compile(
            r"\b(approve my loan|home loan|guarantee return|guaranteed profit|stock pick)\b",
            re.IGNORECASE,
        ),
        re.compile(
            r"\b(approve my passport|government decision|tax evasion)\b", re.IGNORECASE
        ),
    ],
}

# Regex patterns catching prohibited model claims
PROHIBITED_CLAIMS_PATTERNS: list[re.Pattern[str]] = [
    re.compile(
        r"\bi am (actually |a )?human(?! (help|assistance|request|support|team))\b",
        re.IGNORECASE,
    ),
    re.compile(r"\bi verified this\b", re.IGNORECASE),
    re.compile(r"\bi contacted (the )?authorities\b", re.IGNORECASE),
    re.compile(r"\bi called (someone|police|hospital)\b", re.IGNORECASE),
    re.compile(r"\bi approved your (application|loan|passport)\b", re.IGNORECASE),
    re.compile(r"\bi guarantee (success|profit|approval)\b", re.IGNORECASE),
    re.compile(
        r"\bi know (today's|current) (market|gold|stock) price\b", re.IGNORECASE
    ),
    re.compile(r"\bi know real-time weather\b", re.IGNORECASE),
    re.compile(r"\bi performed an action outside\b", re.IGNORECASE),
]


class GuardrailEngine:
    """Evaluates input text against safety policies and filters output claims."""

    def check_input(self, user_input: str) -> GuardrailResult:
        """
        Check if user input violates safety guardrails.

        Args:
            user_input: The text spoken or typed by the user.

        Returns:
            GuardrailResult with is_safe status and optional refusal response.
        """
        clean_text = user_input.strip()

        for category, patterns in GUARDRAIL_PATTERNS.items():
            for pattern in patterns:
                if pattern.search(clean_text):
                    logger.warning(
                        "Guardrail Triggered! Category: %s | Match: %s",
                        category,
                        pattern.pattern,
                    )
                    return GuardrailResult(
                        is_safe=False,
                        category=category,
                        refusal_message=DEFAULT_ESCALATION_RESPONSE,
                    )

        return GuardrailResult(is_safe=True)

    def filter_output_claims(self, assistant_response: str) -> str:
        """
        Inspect assistant response for prohibited claims and scrub/refuse if detected.
        Bypasses checks when output is an escalation prompt or tool confirmation response.

        Args:
            assistant_response: Response generated by the LLM.

        Returns:
            Cleaned response or escalation script if a prohibited claim was made.
        """
        response_lower = assistant_response.lower()
        bypass_keywords = [
            "human help",
            "human assistance",
            "human-help",
            "create the request",
            "permission",
            "reference id",
            "esc-",
        ]
        if any(kw in response_lower for kw in bypass_keywords):
            return assistant_response

        for pattern in PROHIBITED_CLAIMS_PATTERNS:
            if pattern.search(assistant_response):
                logger.warning(
                    "Prohibited Claim Prevented! Match: %s | Original Response: '%s'",
                    pattern.pattern,
                    assistant_response,
                )
                return DEFAULT_ESCALATION_RESPONSE

        return assistant_response


# Global singleton instance
guardrail_engine = GuardrailEngine()
